-- =====================================================
-- AI Decision Log Table
-- EU AI Act Compliance - Transparency and Audit Trail
-- =====================================================
-- This table logs all AI agent decisions for compliance,
-- transparency, and bias monitoring requirements.

CREATE TABLE IF NOT EXISTS public.ai_decision_log (
    -- Primary identifier
    id UUID PRIMARY KEY,

    -- Agent information
    agent_type TEXT NOT NULL CHECK (agent_type IN ('sequence', 'music', 'meditation', 'research')),
    model_used TEXT NOT NULL,
    strictness_level TEXT NOT NULL CHECK (strictness_level IN ('strict', 'guided', 'autonomous')),

    -- User context
    user_id TEXT NOT NULL,

    -- Timing
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processing_time_ms FLOAT NOT NULL,

    -- Decision details
    input_parameters JSONB NOT NULL,
    output_data JSONB NOT NULL,
    confidence_score FLOAT NOT NULL CHECK (confidence_score >= 0.0 AND confidence_score <= 1.0),
    reasoning TEXT NOT NULL,

    -- Success flag
    success BOOLEAN NOT NULL DEFAULT TRUE
);

-- =====================================================
-- Indexes for Performance
-- =====================================================

-- Index on timestamp for time-based queries
CREATE INDEX IF NOT EXISTS idx_ai_decision_log_timestamp
ON public.ai_decision_log (timestamp DESC);

-- Index on user_id for user-specific queries
CREATE INDEX IF NOT EXISTS idx_ai_decision_log_user_id
ON public.ai_decision_log (user_id);

-- Index on agent_type for agent-specific analysis
CREATE INDEX IF NOT EXISTS idx_ai_decision_log_agent_type
ON public.ai_decision_log (agent_type);

-- Index on success flag for failure analysis
CREATE INDEX IF NOT EXISTS idx_ai_decision_log_success
ON public.ai_decision_log (success) WHERE success = FALSE;

-- Composite index for common query patterns
CREATE INDEX IF NOT EXISTS idx_ai_decision_log_agent_timestamp
ON public.ai_decision_log (agent_type, timestamp DESC);

-- =====================================================
-- Row Level Security (RLS) - Optional
-- =====================================================
-- Uncomment if you want to enable RLS for additional security

-- ALTER TABLE public.ai_decision_log ENABLE ROW LEVEL SECURITY;

-- -- Allow service role full access
-- CREATE POLICY "Service role has full access to ai_decision_log"
-- ON public.ai_decision_log
-- FOR ALL
-- TO service_role
-- USING (true)
-- WITH CHECK (true);

-- -- Users can only see their own decision logs
-- CREATE POLICY "Users can view their own decision logs"
-- ON public.ai_decision_log
-- FOR SELECT
-- TO authenticated
-- USING (auth.uid()::text = user_id);

-- =====================================================
-- Comments for Documentation
-- =====================================================

COMMENT ON TABLE public.ai_decision_log IS 'EU AI Act compliance table logging all AI agent decisions for transparency, audit, and bias monitoring';
COMMENT ON COLUMN public.ai_decision_log.id IS 'Unique decision identifier (UUID)';
COMMENT ON COLUMN public.ai_decision_log.agent_type IS 'Type of AI agent: sequence, music, meditation, or research';
COMMENT ON COLUMN public.ai_decision_log.model_used IS 'LLM model name used for the decision (e.g., gpt-3.5-turbo)';
COMMENT ON COLUMN public.ai_decision_log.strictness_level IS 'Agent strictness level: strict, guided, or autonomous';
COMMENT ON COLUMN public.ai_decision_log.user_id IS 'User who triggered the agent decision';
COMMENT ON COLUMN public.ai_decision_log.timestamp IS 'When the decision was made (UTC)';
COMMENT ON COLUMN public.ai_decision_log.processing_time_ms IS 'Time taken to process the request in milliseconds';
COMMENT ON COLUMN public.ai_decision_log.input_parameters IS 'Input parameters provided to the agent (JSONB)';
COMMENT ON COLUMN public.ai_decision_log.output_data IS 'Output data generated by the agent (JSONB)';
COMMENT ON COLUMN public.ai_decision_log.confidence_score IS 'Confidence score between 0.0 and 1.0';
COMMENT ON COLUMN public.ai_decision_log.reasoning IS 'Human-readable explanation of the decision';
COMMENT ON COLUMN public.ai_decision_log.success IS 'Whether the agent processing succeeded or failed';

-- =====================================================
-- Verification Query
-- =====================================================
-- Run this after creating the table to verify structure:
-- SELECT column_name, data_type, is_nullable
-- FROM information_schema.columns
-- WHERE table_name = 'ai_decision_log'
-- ORDER BY ordinal_position;
