-- =====================================================
-- MIGRATION: Populate GAA/Hurling Sport Exercises
-- Date: March 2024
-- Description: Adds GAA/Hurling-specific Pilates exercises to sport_exercises table
-- =====================================================

-- Clear any existing GAA data first
DELETE FROM sport_exercises WHERE sport = 'gaa';

-- Insert GAA/Hurling exercises
INSERT INTO sport_exercises (sport, exercise_name, category, description, sport_relevance, injury_prevention, position_specific, variations, muscle_groups)
VALUES
-- Warm-up exercises
('gaa', 'The Hundred', 'Warm-up',
'Classic Pilates breathing exercise. Pump arms up and down 100 times while maintaining neutral spine and engaged core. Inhale for 5 pumps, exhale for 5 pumps.',
'Builds core endurance essential for maintaining strong positioning during matches. The breathing pattern helps hurlers develop stamina for high-intensity rallies.',
'Strengthens deep core muscles that protect the spine during rotational movements in hurling. Prevents lower back injuries common from repetitive striking motions.',
'All positions benefit. Particularly valuable for midfielders who need sustained core strength for aerial battles and long-distance striking.',
'{"u12mod": "Reduce to 50 pumps with bent knees. Focus on breathing pattern over speed."}',
ARRAY['core', 'breathing']),

('gaa', 'Roll-Up', 'Warm-up',
'Articulate spine one vertebra at a time from lying to seated. Arms reach forward, maintaining C-curve in spine.',
'Develops spinal flexibility crucial for the range of motion needed in ground hurling and overhead striking. Builds control through the striking motion arc.',
'Promotes healthy spinal mechanics, reducing risk of disc injuries from repetitive bending to pick up sliotar. Strengthens back extensors.',
'Essential for defenders who frequently bend to block and hook. Goalkeepers benefit from improved spine articulation for save movements.',
'{"u12mod": "Use resistance band for assistance. Allow slight knee bend if needed."}',
ARRAY['core', 'spine', 'flexibility']),

('gaa', 'Rolling Like a Ball', 'Warm-up',
'Balance on sit bones, knees to chest, roll back to shoulders and return to balance. Maintain tight ball shape throughout.',
'Enhances balance and body awareness crucial for maintaining stability during physical contests. Develops the quick recovery needed after collisions.',
'Massages spine and develops proprioception, reducing risk of falls and awkward landings. Strengthens deep core stabilizers.',
'Excellent for all players, especially those in contested positions. Helps develop the body control needed for aerial challenges.',
'{"u12mod": "Hold static balance position for 5 seconds between rolls. Keep rolls small and controlled."}',
ARRAY['balance', 'core', 'coordination']),

-- Core exercises
('gaa', 'Single Leg Stretch', 'Core',
'Alternate bringing knees to chest while maintaining neutral pelvis. Head and shoulders lifted, hands guide knee position.',
'Mimics the single-leg stability required during striking motion. Develops core control while limbs move independently - essential for hurling technique.',
'Prevents hip flexor strains common in hurling. Builds balanced strength between both sides, reducing compensation injuries.',
'Critical for forwards who need precise striking technique. Helps all positions maintain balance during dynamic movements.',
'{"u12mod": "Keep head down if neck tires. Focus on maintaining neutral pelvis over speed."}',
ARRAY['core', 'hip_flexors', 'stability']),

('gaa', 'Double Leg Stretch', 'Core',
'Extend arms overhead and legs to 45 degrees simultaneously, then circle arms and draw knees back to chest.',
'Builds the explosive core strength needed for powerful striking and long-range passing. Develops coordination for full-body movements.',
'Strengthens the anterior chain while maintaining spinal stability, crucial for preventing back injuries during explosive movements.',
'Particularly beneficial for midfielders and half-backs who need powerful long-range striking ability.',
'{"u12mod": "Keep legs higher (60 degrees) to reduce strain. Arms can reach forward instead of overhead."}',
ARRAY['core', 'coordination', 'strength']),

('gaa', 'Single Straight Leg', 'Core',
'Scissor straight legs up and down while maintaining neutral spine. Quick tempo with controlled movement.',
'Develops the rapid leg movement and core stability needed for quick changes of direction while maintaining balance with hurley in hand.',
'Prevents hamstring strains by building eccentric strength. Addresses muscle imbalances between legs.',
'Vital for corner-backs and full-backs who need rapid footwork for marking and intercepting.',
'{"u12mod": "Allow slight knee bend. Reduce range of motion, keeping legs higher."}',
ARRAY['core', 'hamstrings', 'hip_flexors']),

('gaa', 'Double Straight Leg', 'Core',
'Lower and lift both straight legs together while maintaining neutral spine. Hands support lower back.',
'Builds the deep core strength required to maintain stability during overhead striking and catching high balls.',
'Protects lower back during jumping and landing movements. Strengthens the transverse abdominis crucial for spinal stability.',
'Essential for all positions, particularly important for players competing for puck-outs and high balls.',
'{"u12mod": "Bend knees to tabletop position. Focus on keeping lower back pressed down."}',
ARRAY['core', 'lower_abs']),

('gaa', 'Criss-Cross', 'Core',
'Rotate torso bringing opposite elbow toward knee. Alternate sides with controlled rotation through center.',
'Directly trains the rotational power needed for striking. Develops the oblique strength essential for powerful shots on goal.',
'Builds balanced rotational strength, preventing the one-sided development that can lead to injury in hurling.',
'Critical for forwards needing powerful striking from various angles. Half-backs benefit from improved passing range.',
'{"u12mod": "Keep feet on ground, just rotate upper body. Move slowly with control."}',
ARRAY['obliques', 'core', 'rotation']),

-- Full body integration
('gaa', 'Cork-Screw', 'Full Body',
'Circle legs together in controlled motion while maintaining stable torso. Advanced core and control exercise.',
'Develops the multi-directional core control needed when striking from awkward positions or while off-balance.',
'Builds resilience in the core musculature against rotational forces, protecting the spine during contact.',
'Particularly useful for forwards who often need to strike while being challenged by defenders.',
'{"u12mod": "Perform with knees bent. Make smaller circles, focus on control."}',
ARRAY['core', 'obliques', 'control']),

('gaa', 'Saw', 'Full Body',
'Seated spinal rotation with forward reach. Twist and reach past opposite foot with controlled breathing.',
'Enhances the thoracic rotation essential for generating power in striking. Improves flexibility for overhead pulling and striking.',
'Addresses thoracic spine mobility restrictions common in hurlers. Prevents compensatory lower back movement.',
'Valuable for all positions to maintain spinal health and rotational range of motion throughout long matches.',
'{"u12mod": "Reduce rotation range. Focus on tall seated posture rather than forward reach."}',
ARRAY['rotation', 'hamstrings', 'spine']),

('gaa', 'Neck Pull', 'Full Body',
'Roll up with hands behind head, maintaining neutral neck. Challenges core control and spinal articulation.',
'Builds the neck and upper back strength needed for aerial challenges and to maintain head position during contact.',
'Strengthens deep neck flexors, reducing risk of neck injuries during collisions and headers.',
'Important for players in physical positions where contact is frequent. Helps maintain proper head position during play.',
'{"u12mod": "Perform standard Roll-Up instead. Build up to this advanced version gradually."}',
ARRAY['core', 'neck', 'spine']),

('gaa', 'Spine Twist', 'Full Body',
'Seated rotation with arms extended. Pure transverse plane movement maintaining vertical axis.',
'Improves rotational mobility essential for scanning the field while maintaining hurley position. Enhances passing range.',
'Promotes healthy spinal rotation patterns, reducing stress on individual vertebrae during quick turning movements.',
'Crucial for center-backs and half-backs who need excellent field vision and passing range.',
'{"u12mod": "Arms crossed at chest to reduce lever length. Smaller range of motion."}',
ARRAY['rotation', 'spine', 'posture']),

('gaa', 'Open Leg Rocker', 'Full Body',
'Balance on sit bones with legs extended in V. Rock back to shoulders and return to balance.',
'Challenges the dynamic balance needed when competing for possession while off-balance. Builds reactive stability.',
'Develops proprioception and core strength simultaneously, reducing risk of falls and awkward movements.',
'Beneficial for all players, especially those frequently involved in ground hurling and contested possessions.',
'{"u12mod": "Keep knees bent. Hold balance position statically before attempting rocks."}',
ARRAY['balance', 'core', 'flexibility']),

-- Hip and leg focus
('gaa', 'Scissors', 'Lower Body',
'Alternating straight leg lifts with hands supporting raised leg. Quick tempo maintaining pelvic stability.',
'Develops the explosive hip flexion needed for sprinting to contest possession. Builds single-leg control for striking.',
'Prevents hip flexor and hamstring strains through controlled lengthening and strengthening.',
'Essential for wing positions requiring repeated sprinting. Valuable for all players covering distance.',
'{"u12mod": "Reduce range of motion. Support head with one hand if needed."}',
ARRAY['hip_flexors', 'hamstrings', 'core']),

('gaa', 'Bicycle', 'Lower Body',
'Simulated cycling motion while supine. Maintain neutral spine throughout movement.',
'Mimics the leg drive pattern used in sprinting and change of direction. Builds endurance for repeated efforts.',
'Balanced strengthening of hip flexors and extensors, preventing overuse injuries common in running sports.',
'Particularly valuable for positions requiring repeated short sprints and recovery.',
'{"u12mod": "Smaller range of motion, moving legs higher. Can keep head down."}',
ARRAY['hip_flexors', 'endurance', 'coordination']),

('gaa', 'Shoulder Bridge', 'Lower Body',
'Articulated bridge with single leg variations. Maintain level pelvis during leg movements.',
'Builds the posterior chain power essential for acceleration and jumping. Develops glute strength for powerful striking.',
'Prevents knee injuries by strengthening glutes and reducing quad dominance. Addresses lower back issues.',
'Critical for all positions, especially those requiring explosive movements and jumping ability.',
'{"u12mod": "Keep both feet down for basic bridge. Focus on proper glute activation."}',
ARRAY['glutes', 'hamstrings', 'core']),

('gaa', 'Side Kicks (Kneeling)', 'Lower Body',
'Kneeling side plank position with leg movements. Maintain stable torso while leg moves freely.',
'Develops lateral stability crucial for side-stepping opponents and maintaining balance during physical challenges.',
'Strengthens hip stabilizers, preventing knee injuries from cutting movements. Builds lateral chain strength.',
'Important for defenders who need quick lateral movement for marking. Benefits all positions requiring agility.',
'{"u12mod": "Perform lying on side instead of kneeling. Smaller movement range."}',
ARRAY['hip_stabilizers', 'glutes', 'balance']),

('gaa', 'Side Kick Series', 'Lower Body',
'Multiple leg movements in side-lying position: front/back, up/down, circles. Maintain neutral alignment.',
'Comprehensive hip strengthening for the multi-directional demands of hurling. Builds control through full range.',
'Addresses all planes of hip movement, preventing overuse injuries and muscle imbalances.',
'Beneficial for all players to maintain hip health and function throughout the season.',
'{"u12mod": "Reduce number of repetitions. Support head with bottom arm."}',
ARRAY['hips', 'glutes', 'stability']),

-- Back extension series
('gaa', 'Single Leg Kick', 'Back Extension',
'Prone hamstring curls with emphasis on glute engagement. Maintain neutral pelvis throughout.',
'Builds the hamstring and glute strength needed for explosive acceleration and deceleration in hurling.',
'Prevents hamstring strains by building eccentric strength. Promotes proper posterior chain activation.',
'Essential for all positions, particularly those requiring repeated sprinting efforts.',
'{"u12mod": "Reduce range of motion. Focus on proper form over speed."}',
ARRAY['hamstrings', 'glutes', 'back']),

('gaa', 'Double Leg Kick', 'Back Extension',
'Prone position, both legs kick while arms reach back. Lift chest into extension as legs lower.',
'Develops the back extension strength needed for maintaining upright posture during long matches. Counteracts forward-bent positions.',
'Strengthens erector spinae muscles, preventing lower back fatigue and injury during matches.',
'Important for all players to maintain spinal health and combat the forward-leaning posture of hurling stance.',
'{"u12mod": "Smaller range of motion in both legs and spine. Can keep arms by sides."}',
ARRAY['back_extensors', 'hamstrings', 'shoulders']),

('gaa', 'Swimming', 'Back Extension',
'Prone opposite arm/leg lifts with swimming motion. Maintain neutral spine and steady breathing.',
'Builds the cross-body coordination essential for maintaining balance during striking and running with the hurley.',
'Develops balanced back strength, preventing the asymmetries that can develop from one-sided striking.',
'Valuable for all positions to maintain posterior chain endurance throughout matches.',
'{"u12mod": "Lift one limb at a time instead of opposite pairs. Reduce tempo."}',
ARRAY['back', 'coordination', 'endurance']),

('gaa', 'Swan Dive', 'Back Extension',
'Rock between back extension and forward fold in prone position. Advanced back strength exercise.',
'Builds the explosive back extension needed for competing for high balls and overhead striking.',
'Strengthens the entire posterior chain, protecting against impact injuries during aerial challenges.',
'Particularly important for players frequently competing for puck-outs and high balls.',
'{"u12mod": "Hold static swan position instead of rocking. Build strength before adding movement."}',
ARRAY['back_extensors', 'control', 'strength']),

-- Plank variations
('gaa', 'Leg Pull Front', 'Plank Series',
'Plank position with alternating leg lifts. Maintain neutral spine and level pelvis.',
'Builds the anti-rotational stability needed when striking or being challenged while in possession.',
'Develops core stability in all planes, protecting the spine during contact and rotational movements.',
'Essential for all players to maintain trunk stability during dynamic play.',
'{"u12mod": "Hold static plank. Progress to knee lifts before attempting full leg lifts."}',
ARRAY['core', 'shoulders', 'stability']),

('gaa', 'Leg Pull Back', 'Plank Series',
'Reverse plank with leg lifts. Challenges posterior chain and shoulder stability.',
'Strengthens the posterior chain needed for backward movement and defensive positioning.',
'Builds shoulder stability for overhead movements and posterior strength for injury prevention.',
'Particularly valuable for defenders who need to track backwards while maintaining visual contact.',
'{"u12mod": "Hold static reverse plank with bent knees. Build strength progressively."}',
ARRAY['glutes', 'shoulders', 'hamstrings']),

('gaa', 'Kneeling Side Kick', 'Plank Series',
'Side plank on knee with top leg movements. Maintain alignment while leg moves dynamically.',
'Develops the lateral stability essential for cutting movements and maintaining balance during challenges.',
'Strengthens lateral stabilizers, preventing ankle and knee injuries from directional changes.',
'Important for all players, especially those in positions requiring quick direction changes.',
'{"u12mod": "Side-lying position instead of kneeling. Focus on maintaining alignment."}',
ARRAY['obliques', 'hip_stabilizers', 'balance']),

-- Advanced exercises
('gaa', 'Teaser', 'Advanced',
'V-sit balance position with variations. Ultimate core strength and control challenge.',
'Builds exceptional core strength for maintaining stability during aerial challenges and powerful striking.',
'Develops deep core strength that protects the spine during high-impact movements.',
'Beneficial for experienced players looking to maximize core power and control.',
'{"u12mod": "One leg teaser or supported with hands behind thighs. Build progressively."}',
ARRAY['core', 'hip_flexors', 'balance']),

('gaa', 'Hip Twist', 'Advanced',
'Seated position with hands behind, circle legs while maintaining lifted chest.',
'Develops rotational control essential for striking accuracy from various positions.',
'Builds oblique and deep core strength, protecting against rotational injuries.',
'Valuable for forwards who need to strike accurately from difficult angles.',
'{"u12mod": "Keep feet on ground, focus on upper body stability. Progress gradually."}',
ARRAY['obliques', 'core', 'hip_flexors']),

('gaa', 'Control Balance', 'Advanced',
'Balance on shoulders with legs extended overhead, lower one leg at a time with control.',
'Challenges total body control and awareness needed for maintaining technique under pressure.',
'Builds exceptional core and shoulder stability, preventing injuries during falls or collisions.',
'Advanced exercise for experienced players seeking maximum body control.',
'{"u12mod": "Practice shoulder stand first. Use wall for support initially."}',
ARRAY['core', 'balance', 'control']),

('gaa', 'Push-Up Series', 'Advanced',
'Traditional push-ups with Pilates principles. Include variations and single-leg options.',
'Builds upper body strength essential for physical contests and maintaining possession under pressure.',
'Develops functional pushing strength while maintaining core stability, preventing shoulder injuries.',
'Important for all players involved in physical contests for possession.',
'{"u12mod": "Wall or incline push-ups. Focus on proper form over quantity."}',
ARRAY['chest', 'shoulders', 'core']),

('gaa', 'Rocking', 'Advanced',
'Prone back extension with ankle hold, rock forward and back maintaining shape.',
'Develops the posterior chain power and flexibility needed for explosive movements in hurling.',
'Builds back strength and hip flexor flexibility simultaneously, addressing common imbalances.',
'Advanced exercise for players with good flexibility and strength base.',
'{"u12mod": "Hold static position without rocking. Use strap for ankles if needed."}',
ARRAY['back', 'flexibility', 'strength']),

-- Stretching and flexibility
('gaa', 'Spine Stretch Forward', 'Flexibility',
'Seated forward fold emphasizing spinal articulation over hamstring stretch.',
'Improves spinal flexibility for the varied positions required in ground hurling and ball pickup.',
'Promotes healthy disc spacing and reduces compression from impact and running.',
'Important for all players to maintain spinal health and flexibility.',
'{"u12mod": "Sit on raised surface if needed. Focus on rounding spine over reaching forward."}',
ARRAY['spine', 'hamstrings', 'flexibility']),

('gaa', 'Seal', 'Flexibility',
'Similar to Rolling Like a Ball but with arm position creating shoulder stretch. Clap feet three times.',
'Adds coordination challenge while developing the balance needed for contested situations.',
'Promotes spinal mobility and massage, helping recovery between training sessions.',
'Useful cool-down exercise for all players, adds playful element to training.',
'{"u12mod": "Perform without clapping. Focus on controlled rolling motion."}',
ARRAY['balance', 'flexibility', 'coordination']),

('gaa', 'Mermaid Stretch', 'Flexibility',
'Seated side bend with various arm positions. Emphasizes lateral spine flexibility.',
'Develops the lateral flexibility needed for reaching to hook or block while maintaining balance.',
'Addresses lateral chain tightness common from rotational sports. Prevents rib and oblique strains.',
'Beneficial for all positions to maintain lateral spine mobility.',
'{"u12mod": "Support with hand on ground. Smaller range of motion."}',
ARRAY['obliques', 'flexibility', 'spine']),

-- Standing work
('gaa', 'Standing Roll Down', 'Standing',
'Standing spinal articulation to forward fold and return. Weight distribution awareness.',
'Teaches proper bending mechanics for picking up sliotar. Builds awareness of weight transfer.',
'Prevents back injuries by promoting proper movement patterns for bending and lifting.',
'Essential movement pattern for all players throughout match play.',
'{"u12mod": "Bend knees as needed. Focus on sequential spinal movement."}',
ARRAY['spine', 'hamstrings', 'control']),

('gaa', 'Standing Single Leg Balance', 'Standing',
'Various single leg balance challenges with movement variations.',
'Directly applicable to striking stance and follow-through. Builds proprioception for uneven surfaces.',
'Prevents ankle injuries and improves recovery from off-balance positions.',
'Critical for all players, especially on wet or uneven pitches.',
'{"u12mod": "Use wall or chair for light support. Reduce movement complexity."}',
ARRAY['balance', 'proprioception', 'stability']),

('gaa', 'Standing Side Leg Series', 'Standing',
'Standing hip abduction, adduction, and circles. Maintain pelvic stability throughout.',
'Builds hip stability for cutting movements and maintaining balance during physical challenges.',
'Strengthens hip stabilizers crucial for knee injury prevention.',
'Important for all positions requiring agility and direction changes.',
'{"u12mod": "Use support for balance. Smaller range of motion."}',
ARRAY['hips', 'balance', 'stability']),

('gaa', 'Standing Arms Series', 'Standing',
'Standing arm exercises focusing on shoulder stability and postural muscles.',
'Develops shoulder endurance for maintaining hurley position throughout matches.',
'Prevents shoulder overuse injuries and promotes proper posture.',
'Valuable for all players to maintain shoulder health and striking efficiency.',
'{"u12mod": "Use lighter resistance or no resistance. Focus on proper form."}',
ARRAY['shoulders', 'posture', 'endurance']);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_sport_exercises_gaa ON sport_exercises(sport) WHERE sport = 'gaa';
CREATE INDEX IF NOT EXISTS idx_sport_exercises_gaa_category ON sport_exercises(sport, category) WHERE sport = 'gaa';